Update Plugin.swift
epicshaggy/capacitor-native-biometric pull request #47
Opened 2022-04-07 08:53 UTC by danyyacoub

fix for swift 5

2022-04-07 15:05 UTC, riderx commented on package.json
> -    "url": "https://github.com/epicshaggy/capacitor-native-biometric"
you need to remove this change to make allow merge

2022-04-07 15:05 UTC, riderx commented on package.json
> -    "url": "https://github.com/epicshaggy/capacitor-native-biometric/issues"
same here

2022-04-07 15:05 UTC, riderx commented on package.json
> -  "author": "Jose Martinez",
same here

2022-04-12 09:44 UTC, squio commented
Quick comment about this PR: I'm not the maintainer but I suppose the `dist` and all other extraneous files shouldn't be part of the VCS; just the two updated `getBool()` calls in the single swift file should be enough?

2022-04-12 16:46 UTC, riderx commented
@squio  agree i do think he did that to allow npm i from github.
2 branch should exist, one to use before it's merge and one for the merge

2022-04-12 20:23 UTC, danyyacoub commented
Yes exactly @riderx , i was trying to be able to make the npm install (you can see from the commits that it was a trial and error to make the npm i work :D )
I'll clean it up once i get a sense how to do it properly

2022-04-12 20:24 UTC, riderx commented
@danyyacoub if you need help i can help :)

2022-04-12 20:59 UTC, danyyacoub commented
Thank you @riderx , yes indeed, I actually took into account your note but still have several issues (the package is synced correctly but issues with the postinstall  build and syncing the plugins with android and ios), I used for reference the following 2 links 

https://blaipratdesaba.com/how-to-use-an-npm-node-module-that-has-been-forked-b7dd522fdd08

https://stackoverflow.com/questions/40528053/npm-install-and-build-of-forked-github-repo

I'm not using this fork for the time being but I'd love to have this experience and since this fork is already public i'd want to to make it clean and usable.

Thanks again

2022-04-13 01:08 UTC, riderx commented
Hey @danyyacoub i do think the best way to make it publicly usable is to publish it in npm under your name :
https://jamescalmus.medium.com/how-to-publish-a-scoped-npm-package-for-your-organization-767af1c99b9f

that will result something like npm i @danyyacoub/capacitor-native-biometric` to use it.

when setting is done like in the tutorial you have to :
`npm run build & npm publish` and you are done :)

if you never create account in npm :
https://docs.npmjs.com/creating-a-new-npm-user-account

2022-04-14 06:05 UTC, adirery commented
what's missing to get the merge?

2022-04-14 12:21 UTC, riderx commented
@andrasnobank the PR include more than just the necessary changes, and there are no answers of @epicshaggy

2022-04-21 08:56 UTC, WuglyakBolgoink commented
I'm not approve this PR because it contain a lot of unnecessary code changes. please close this PR without merge and create another one with dedicated changes related **ONLY** to Swift!!!

2022-04-21 08:58 UTC, WuglyakBolgoink requested changes
**NOT APPROVED**! see my last comment!

2022-04-21 15:14 UTC, riderx commented
@WuglyakBolgoink @epicshaggy i made the PR with only what was necessary https://github.com/epicshaggy/capacitor-native-biometric/pull/53

2022-06-11 01:39 UTC, riderx commented
PR can be close work have been done for it

2022-08-09 16:14 UTC, closed without merging